apiVersion: v1
kind: ConfigMap

metadata:
  name: prometheus-config
  namespace: default

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      # Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets:
              - 'localhost:9090'

      # API Gateway
      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'api-gateway:8080'

      # Eureka
      - job_name: 'service-registry'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'service-registry:8761'

      # Config Server
      - job_name: 'config-server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'config-server:8888'

      # Account Service
      - job_name: 'account-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'account-service:8082'

      # Customer Service
      - job_name: 'customer-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'customer-service:8081'

      # Transaction Service
      - job_name: 'transaction-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'transaction-service:8083'

      # Auth Service
      - job_name: 'auth-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'auth-service:8084'